sudo: required

services:
  - docker

script:
  - docker-compose build && docker-compose run test

# Ugly, see http://stackoverflow.com/a/24600210/3465375
# Handle git submodules yourself
git:
    submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive